### ISSUE TITLE
No friends in friend's TOP on Quest 2

### ISSUE THREAD

**Issue by DarkOutX** [ScoreSaber/scoresaber-quest#18]
I don't see friends in friend-only scores. However, friend score exists in global list and also visible in friend's TOP in PC Beat Saber v1.29 (legacy)

Same problem with both versions 2.2.0 and 2.3.0 on Beat Saber v1.28

Please, let me know how to collect additional debug info if needed

**Comment by Qwasyx** [comment]
Did you add the playerids of each other to /sdcard/ModData/com.beatgames.beatsaber/Mods/ScoreSaber/friends.txt ? The quest version of the Plugin is not able to automatically fetch your steam friends unfortunately.

**Comment by DarkOutX** [comment]
> Did you add their playerid to /sdcard/ModData/com.beatgames.beatsaber/Mods/ScoreSaber/friends.txt ? The quest version of the Plugin is not able to automatically fetch your steam friends unfortunately.

Oh, thanks! Now everything is fine.
